exam/urls.py
from django.urls import path
from . import views

app_name = "exam"

urlpatterns = [

    path('add-exam/', views.AddExamView, name='add_exam'),
    path('exam-detail/<int:id>/', views.ExamDetailView, name='exam_detail'),
    path('edit-exam/<int:id>/', views.EditExamView, name='edit_exam'),
    path('all-exam/', views.AllExamView, name='all_exam'),

]

exam_portal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("radmin.urls")),
    path("", include("sadmin.urls")),

    path("", include("student.urls")),
    path("", include("exam.urls")),
    path("", include("theory.urls")),
    path("", include("nomination_form.urls")),
    path("", include("result.urls")),

    path("", include("question.urls")),
    path("", include("answer.urls")),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

	path("", views.LoginView, name="login"),
	path("sign-up/", views.SignUpView, name="sign_up"),

	path("e/<str:exam_slug>/<str:exam_link>/", views.ExamLoginView, name="exam_login"),
	path("e/<str:exam_link>/<int:student_id>/start/", views.TakeExamView, name="take_exam"),
	path("e/<str:exam_link>/<int:student_id>/<int:result_id>/nomination_form/", views.TakeExamNView, name="take_exam_n"),
	path("e/<str:exam_link>/<int:student_id>/<int:result_id>/theory/", views.TakeExamTView, name="take_exam_t"),
	path("e/<str:exam_link>/<int:student_id>/exam-complete/", views.ExamCompleteView, name="exam_complete"),
	path("e/<str:exam_link>/<int:student_id>/error/", views.ErrorView, name="error"),

	path("e/<str:exam_slug>/exam-complete/result-checker/", views.ResultCheckerView, name="result_checker"),
	path("e/<str:exam_slug>/<int:student_id>/exam_complete/result-checker/complete/", views.StudentResultView, name="student_result"),

	path("e/time-up-submit/<str:exam_link>/<int:student_id>/r/complete-time-up-submit/", views.TimeUpSubmitView, name="time_up_submit"),
	
	path("userlogout/", views.UserLogoutView, name="userlogout"),

]

radmin/urls.py
from django.urls import path
from . import views

app_name = "radmin"

urlpatterns = [

	path("radmin/", views.IndexView, name="radmin"),
	#path("radmin/", views.IndexView, name="radmin"),

]

result/urls.py
from django.urls import path
from . import views

app_name = "result"

urlpatterns = [

    path('add-result/', views.AddResultView, name='add_result'),
    path('result-detail/<int:result_id>/<int:student_id>/', views.ResultDetailView, name='result_detail'),
    path('edit-result/<int:result_id>/<int:student_id>/', views.EditResultView, name='edit_result'),
    path('all-result/', views.AllResultView, name='all_result'),

]

student/urls.py
from django.urls import path
from . import views

app_name = "student"

urlpatterns = [

    path('add-student/', views.AddStudentView, name='add_student'),
    path('student-detail/<int:id>/', views.StudentDetailView, name='student_detail'),
    path('edit-student/<int:id>/', views.EditStudentView, name='edit_student'),
    path('all-student/', views.AllStudentView, name='all_student'),

]

radmin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class RAdmin(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=500)
	status = models.CharField(max_length=500, default="not-verified")

	pub_date = models.DateTimeField(default=timezone.now)
	def __str__(self):
		return self.user.username

radmin/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def IndexView(request):
	if request.user.is_superuser == True:
		if request.method == "POST":
			pass
			
		else:
			context = {}
			return render(request, "radmin/index.html", context)
			
	else:
		return HttpResponse("Не авторизованы!, Свяжитесь с номером 87074440969")		

radmin/templates/radmin/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Портал экзаменации- Панель админа</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'radmin/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'radmin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'radmin/plugins/adminlte.min.css' %}">
</head>

<div class="wrapper">

  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      </li>
      <li class="nav-item d-none d-sm-inline-block"> 
        <a href="{% url 'radmin:radmin' %}" class="nav-link">Вы залогинились как:<b> {{ request.user.username }}</b></a>
      </li>
    </ul>

  </nav>
  <!-- /.navbar -->

  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'radmin:radmin' %}" class="brand-link">
      <span class="brand-text font-weight-light">Экзаменационный портал</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
          <a href="{% url 'radmin:radmin' %}" class="d-block">{{ request.user.username }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="{% url 'radmin:radmin' %}" class="nav-link" style="background-color: #28a745;">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Главная
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>

          <li class="nav-item has-treeview menu-open">
            <a href="{% url 'student:add_student' %}" class="nav-link" style="background-color: #28a745;">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Добавить учащегося
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>

          <li class="nav-item has-treeview menu-open">
            <a href="{% url 'student:all_student' %}" class="nav-link" style="background-color: #28a745;">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Посмотреть учащихся
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>

          <li class="nav-item has-treeview menu-open">
            <a href="{% url 'exam:add_exam' %}" class="nav-link" style="background-color: #28a745;">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Добавить экзамен
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>

          <li class="nav-item has-treeview menu-open">
            <a href="{% url 'exam:all_exam' %}" class="nav-link" style="background-color: #28a745;">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Посмотреть экзамены
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>

          <li class="nav-item has-treeview menu-open">
            <a href="{% url 'result:all_result' %}" class="nav-link" style="background-color: #28a745;">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Посмотреть результаты
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>


          <li class="nav-item has-treeview menu-open">
            <a href="{% url 'main:userlogout' %}" class="nav-link" style="background-color: #28a745;">
              <i class="nav-icon fas fa-power-off"></i>
              <p>
                Выйти
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <div class="content-wrapper">
    <br />

    <section class="content">
      <div class="container-fluid">

    {% block content %}
      
    {% endblock content %}

      </div>
    </section>

  </div>


  <footer class="main-footer">
    <strong> &copy; 2023 <a href="https://adminlte.io">Портал экзаменации</a></strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Developed by Kuandyshev</b>
    </div>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{% static 'radmin/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'radmin/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'radmin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'radmin/plugins/js/adminlte.js' %}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{% static 'radmin/plugins/js/demo.js' %}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{% static 'radmin/plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>
<script src="{% static 'radmin/plugins/raphael/raphael.min.js' %}"></script>
<script src="{% static 'radmin/plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
<script src="{% static 'radmin/plugins/jquery-mapael/maps/usa_states.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'radmin/plugins/chart.js/Chart.min.js' %}"></script>

<!-- PAGE SCRIPTS -->
<script src="{% static 'radmin/plugins/js/pages/dashboard2.js' %}"></script>



<script>
  // Set the date we're counting down to
  var countDownDate = new Date("{{ project.delivery_date }}").getTime();

  // Update the count down every 1 second
  var x = setInterval(function() {

    // Get today's date and time
    var now = new Date().getTime();


    // Find the distance between now and the count down date
    var distance = countDownDate - now;
    //var distance = "{{ counter }}";

    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    document.getElementById("ray_counter").innerHTML = days + "d " + hours + "h "
    + minutes + "m " + seconds + "s ";

    // If the count down is finished, write some text
    if (distance < 0) {
      clearInterval(x);
      document.getElementById("ray_counter").innerHTML = "EXPIRED";
    }
  }, 1000);
</script>
</body>
</html>

radmin/templates/radmin/index.html
{% extends 'radmin/base.html' %}
{% load static %}
  

{% block content %}
     

   	<section class="home-banner-area relative" style="background-image:url({% static 'main/img/header-bg.png'%}); background-size: cover; height: 500px;">
		<div class="container">
			<div class="row fullscreen d-flex align-items-center justify-content-center">
				<div class="banner-content col-lg-5 col-md-5 col-sm-5">
					<br>
					<br>
					<br>
					<br>
					<br>
					<br>
					

					<div class="input-wrap">
						
					</div>
					<h1 class="wow fadeIn" data-wow-duration="4s" style="color: #fff">Мы оцениваем лучших по<br> онлайн экзаменам</h1>

					
				</div>
			</div>
		</div>
		<div class="rocket-img">
			<img src="img/rocket.png" alt="">
		</div>
	</section>
	<!-- End Banner Area -->
       
{% endblock content %}