exam/urls.py
from django.urls import path
from . import views

app_name = "exam"

urlpatterns = [

    path('add-exam/', views.AddExamView, name='add_exam'),
    path('exam-detail/<int:id>/', views.ExamDetailView, name='exam_detail'),
    path('edit-exam/<int:id>/', views.EditExamView, name='edit_exam'),
    path('all-exam/', views.AllExamView, name='all_exam'),

]

exam_portal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("radmin.urls")),
    path("", include("sadmin.urls")),

    path("", include("student.urls")),
    path("", include("exam.urls")),
    path("", include("theory.urls")),
    path("", include("nomination_form.urls")),
    path("", include("result.urls")),

    path("", include("question.urls")),
    path("", include("answer.urls")),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

	path("", views.LoginView, name="login"),
	path("sign-up/", views.SignUpView, name="sign_up"),

	path("e/<str:exam_slug>/<str:exam_link>/", views.ExamLoginView, name="exam_login"),
	path("e/<str:exam_link>/<int:student_id>/start/", views.TakeExamView, name="take_exam"),
	path("e/<str:exam_link>/<int:student_id>/<int:result_id>/nomination_form/", views.TakeExamNView, name="take_exam_n"),
	path("e/<str:exam_link>/<int:student_id>/<int:result_id>/theory/", views.TakeExamTView, name="take_exam_t"),
	path("e/<str:exam_link>/<int:student_id>/exam-complete/", views.ExamCompleteView, name="exam_complete"),
	path("e/<str:exam_link>/<int:student_id>/error/", views.ErrorView, name="error"),

	path("e/<str:exam_slug>/exam-complete/result-checker/", views.ResultCheckerView, name="result_checker"),
	path("e/<str:exam_slug>/<int:student_id>/exam_complete/result-checker/complete/", views.StudentResultView, name="student_result"),

	path("e/time-up-submit/<str:exam_link>/<int:student_id>/r/complete-time-up-submit/", views.TimeUpSubmitView, name="time_up_submit"),
	
	path("userlogout/", views.UserLogoutView, name="userlogout"),

]

exam/models.py
from django.db import models

from student.models import Student
from question.models import Question
from answer.models import  Answer
from theory.models import Theory
from nomination_form.models import NominationForm
from result.models import Result

from django.utils import timezone

# Create your models here.

class Exam(models.Model):
	title = models.CharField(max_length=500)
	exam_slug = models.CharField(max_length=500, default="no slug")
	exam_type = models.CharField(max_length=500)
	batch = models.CharField(max_length=500)

	duration = models.CharField(max_length=500)
	
	students = models.ManyToManyField(Student, through="ExamStudentConnector")
	questions = models.ManyToManyField(Question, through="ExamQuestionConnector")
	answers = models.ManyToManyField(Answer, through="ExamAnswerConnector")

	theorys = models.ManyToManyField(Theory, through="ExamTheoryConnector")

	nomination_forms = models.ManyToManyField(NominationForm, through="ExamNominationFormConnector")

	total_score = models.IntegerField(default=0)

	results = models.ManyToManyField(Result, through="ExamResultConnector")

	status = models.BooleanField(default=False)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		#return self.cart_id
		return str(self.title)




  
class ExamStudentConnector(models.Model):
	exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


  
class ExamQuestionConnector(models.Model):
	exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class ExamAnswerConnector(models.Model):
	exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
	answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class ExamTheoryConnector(models.Model):
	exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
	theory = models.ForeignKey(Theory, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class ExamNominationFormConnector(models.Model):
	exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
	nomination_form = models.ForeignKey(NominationForm, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)


class ExamResultConnector(models.Model):
	exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
	result = models.ForeignKey(Result, on_delete=models.CASCADE)
	pub_date = models.DateTimeField(default=timezone.now)

exam/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from exam.models import Exam

import random
import string



def ray_randomizer(breath=0, length=7):
	landd = string.ascii_letters + string.digits
	return ''.join((random.choice(landd) for i in range(length)))

def AddExamView(request):
	if request.user.is_superuser == True:
		if request.method == "POST":
			title = request.POST.get("title")
			exam_type = request.POST.get("exam_type")
			batch = request.POST.get("batch")
			duration = request.POST.get("duration")

			exam_slug = ray_randomizer(4,10)

			exam = Exam.objects.create(title=title, exam_slug=exam_slug, exam_type=exam_type, batch=batch, duration=duration)
			exam.save()

			return HttpResponseRedirect(reverse("question:add_qa", args=(exam.id,)))
			
		else:
			context = {}
			return render(request, 'exam/add_exam.html', context)
		
	else:
		return HttpResponse("Не авторизованы!, Свяжитесь с номером 87074440969")		





def AddNominationFormView(request, exam_id):
	pass


def AddTheoryiew(request, exam_id):
	pass



def ExamDetailView(request, id):
	if request.user.is_superuser == True:
		if request.method == "POST":
			pass
			
		else:
			exam = Exam.objects.get(id=id)

			context = {"exam": exam}
			return render(request, 'exam/exam_detail.html', context)
		

	else:
		return HttpResponse("Не авторизованы!, Свяжитесь с номером 87074440969")		



def EditExamView(request, id):
	if request.user.is_superuser == True:
		exam = Exam.objects.get(id=id)
		if request.method == "POST":
			title = request.POST.get("title")
			exam_type = request.POST.get("exam_type")
			batch = request.POST.get("batch")
			duration = request.POST.get("duration")

			if request.POST.get("status") == "on":
				status = True
			else:
				status = False

			exam.title = title
			exam.exam_type = exam_type
			exam.batch = batch
			exam.duration = duration

			exam.status = status

			exam.save()

			return HttpResponseRedirect(reverse("exam:all_exam"))
			
		else:
			

			context = {"exam": exam}
			return render(request, 'exam/edit_exam.html', context)


	else:
		return HttpResponse("Не авторизованы!, Свяжитесь с номером 87074440969")		




def AllExamView(request):
	if request.user.is_superuser == True:
		if request.method == "POST":
			pass
			
		else:
			exams = Exam.objects.all()
			context = {"exams": exams}
			return render(request, 'exam/all_exam.html', context)
		

	else:
		return HttpResponse("Не авторизованы!, Свяжитесь с номером 87074440969")		

exam/templates/exam/add_exam.html
{% extends 'radmin/base.html' %}
{% load static %}
  

{% block content %}

                   
                    <form method="post" enctype="multipart/form-data">
                    	{% csrf_token %}
                        <div class="row">
                        

							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="card" style="border-radius: 30px;">
                                    <div class="card-header" style="background-color: #28a745; border-radius:30px 30px 0 0; color: #fff">Добавить экзамен</div>
                                    <div class="card-body">
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Предмет</label>
                                                <input id="cc-pament" name="title" type="text" class="form-control" aria-required="true" aria-invalid="false" required="required">
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Тип Экзамена</label>
                                                <input id="cc-name" name="exam_type" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your email"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" required="required">
                                                <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Поток</label>
                                                <input id="cc-name" name="batch" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your phone"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" required="required">
                                                <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Продолжительнось(сек)</label>
                                                <input id="cc-name" name="duration" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your phone"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" required="required">
                                                <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                                            </div>
                                            <hr>
                                            <br />


                                        
                                    </div>
                                </div>
                            </div>
                                
                                
                                                                
                                
						</div>	
						
						<div class="row">
							<div class="col-lg-12 col-md-8 col-sm-6 col-xs-4">
                                <button id="payment-button" type="submit" class="btn btn-lg btn-block btn btn-success" style="border-radius: 30px;">
                                   <span id="payment-button-amount" class="btn btn-success" style="border-radius: 30px;">Следующая</span>
                                   <span id="payment-button-sending" style="display:none;">Отправка..</span>
                                </button>
                            </div>
						</div>
				 </form>

    <br />
  	
  	

        
       
{% endblock content %}

exam/templates/exam/all_exam.html
{% extends 'radmin/base.html' %}
{% load static %}
  

{% block content %}	

        <div class="row">
          <div class="col-md-12">
            <div class="card" style="border-radius: 30px;">
              <div class="card-header" style="background-color: #28a745; border-radius:30px 30px 0 0; color: #fff">
                <h3 class="card-title">Экзамены</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">№</th>
                      <th>Предмет</th>
                      <th>Экзамен(id)</th>
                      <th>Поток</th>
                      <th>Продолжительность(Minutes)</th>
                      <th>Статус</th>
                      <th>Изменить</th>
                      <th>Ссылка на экзамен</th>
                      <th>Ссылка на результат</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% if exams %}
                      {% for item in exams %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'exam:edit_exam' item.id %}">
                              {{ item.title }}
                            </a>
                        </td>
                        <td>
                          <div>
                            <a href="{% url 'exam:edit_exam' item.id %}">
                              {{ item.exam_type }}({{ item.exam_slug }})
                            </a>
                          </div>
                        </td>
                        <td>
                          <div>
                            <a href="{% url 'exam:edit_exam' item.id %}">
                              {{ item.batch }}
                            </a>
                          </div>
                        </td>
                        <td>
                            <a href="{% url 'exam:edit_exam' item.id %}">
                              {{ item.duration }}
                            </a>
                        </td>
                        <td>
                          <span class="badge bg-success">
                            <a href="{% url 'exam:edit_exam' item.id %}">
                              {{ item.status }}
                            </a>
                          </span>
                        </td>
                        <td>
                            <a href="{% url 'exam:edit_exam' item.id %}">
                              Изменить
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'main:exam_login' item.exam_slug item.id %}">
                             Экзамен
                            </a>
                             <input type="text" value="{% url 'main:exam_login' item.exam_slug item.id %}">
                        </td>
                        <td>
                            <a href="{% url 'main:result_checker' item.exam_slug %}">
                             Результат
                            </a>
                            <input type="text" value="{% url 'main:result_checker' item.exam_slug %}">
                        </td>
                      </tr>
                      {% endfor %}

                    {% else %}
                      <tr>
                        <td>#</td>
                        <td>Извините, ничего не найдено!</td>
                        <td>
                          <div class="progress progress-xs">
                            
                          </div>
                        </td>
                        <td><span class="badge bg-danger"></span></td>
                      </tr>

                    {% endif %}


                  </tbody>
                </table>
              </div>
            </div>

            <!-- /.card -->
          </div>



        </div>
            
{% endblock content %}

exam/templates/exam/edit_exam.html
{% extends 'radmin/base.html' %}
{% load static %}
  

{% block content %}

                   
                    <form method="post" enctype="multipart/form-data">
                    	{% csrf_token %}
                        <div class="row">
                        

							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="card" style="border-radius: 30px;">
                                    <div class="card-header" style="background-color: #28a745; border-radius:30px 30px 0 0; color: #fff">Редактировать Экзамен</div>
                                    <div class="card-body">
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Начать экзамен | не забудьте выбрать статус по умолчанию!</label>
                                                {% if exam.status == False %}
                                                    <select name="status" id="select" class="form-control">
                                                        <option value="off" selected="selected">OFF</option>
                                                        <option value="on">ON</option>
                                                    </select>
                                                {% elif exam.status == True %}
                                                    <select name="status" id="select" class="form-control">
                                                        <option value="off">OFF</option>
                                                        <option value="on" selected="selected">ON</option>
                                                    </select>
                                                {% endif %}
                                            </div>

                                            
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Тема</label>
                                                <input id="cc-pament" name="title" type="text" class="form-control" aria-required="true" aria-invalid="false" value="{{ exam.title }}">
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Тип экзамена</label>
                                                <input id="cc-name" name="exam_type" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your email"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" value="{{ exam.exam_type }}">
                                                <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Поток</label>
                                                <input id="cc-name" name="batch" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your phone"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" value="{{ exam.batch }}">
                                                <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Продолжительность</label>
                                                <input id="cc-name" name="duration" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your phone"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" value="{{ exam.duration}}">
                                                <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                                            </div>
                                            <hr>
                                            <br />


                                        
                                    </div>
                                </div>
                            </div>
                                
                                
                                                                
                                
						</div>	
						
						<div class="row">
							<div class="col-lg-12 col-md-8 col-sm-6 col-xs-4">
                                <button id="payment-button" type="submit" class="btn btn-lg btn-block btn btn-success" style="border-radius: 30px">
                                   <span id="payment-button-amount" class="btn btn-success" style="border-radius: 30px;">Отправить данные</span>
                                   <span id="payment-button-sending" style="display:none;">В процессе..</span>
                                </button>
                            </div>
						</div>
				 </form>

    <br />
  	
  	

        
       
{% endblock content %}