exam/urls.py
from django.urls import path
from . import views

app_name = "exam"

urlpatterns = [

    path('add-exam/', views.AddExamView, name='add_exam'),
    path('exam-detail/<int:id>/', views.ExamDetailView, name='exam_detail'),
    path('edit-exam/<int:id>/', views.EditExamView, name='edit_exam'),
    path('all-exam/', views.AllExamView, name='all_exam'),

]

exam_portal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("radmin.urls")),
    path("", include("sadmin.urls")),

    path("", include("student.urls")),
    path("", include("exam.urls")),
    path("", include("theory.urls")),
    path("", include("nomination_form.urls")),
    path("", include("result.urls")),

    path("", include("question.urls")),
    path("", include("answer.urls")),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

result/urls.py
from django.urls import path
from . import views

app_name = "result"

urlpatterns = [

    path('add-result/', views.AddResultView, name='add_result'),
    path('result-detail/<int:result_id>/<int:student_id>/', views.ResultDetailView, name='result_detail'),
    path('edit-result/<int:result_id>/<int:student_id>/', views.EditResultView, name='edit_result'),
    path('all-result/', views.AllResultView, name='all_result'),

]

result/models.py
from django.db import models

from student.models import Student

from django.utils import timezone

# Create your models here.

class Result(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)

	exam_id = models.CharField(max_length=100, default="none")
	exam_title = models.CharField(max_length=100, default="none")
	exam_type = models.CharField(max_length=100, default="none")
	exam_slug = models.CharField(max_length=100, default="none")

	answers = models.CharField(max_length=100, default="none")
	response_nomination_form_id = models.CharField(max_length=100, default="none")
	response_theory = models.TextField(default="none")

	score = models.IntegerField(default=0)
	total = models.IntegerField(default=0)
	percentage = models.IntegerField(default=0)

	status = models.BooleanField(default=False)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		#return self.cart_id
		return str(self.student.name)

result/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from nomination_form.models import NominationForm
from result.models import  Result
from exam.models import Exam
from student.models import Student

def AddResultView(request):
	if request.method == "POST":
		pass
		
	else:
		context = {}
		return render(request, 'result/add_result.html', context)
		


def AllResultView(request):
	if request.user.is_superuser == True:
		if request.method == "POST":
			pass


		else:
			exams = Exam.objects.all()
			exam_type_list = set()

			for item in exams:
				exam_type_list.add(item.exam_slug)


			#
			grouped_results = []
			for item in exam_type_list:
				results = Result.objects.filter(exam_slug=item)
				if results:
					grouped_results.append(results)
								

			#return HttpResponse(str(grouped_results))
			context = {"results": grouped_results}
			return render(request, 'result/all_result.html', context)


			
	else:
		return HttpResponse("Не авторизованы!, Свяжитесь с номером 87074440969")		



def ResultDetailView(request, result_id, student_id):
	if request.user.is_superuser == True:
		if request.method == "POST":
			student = Student.objects.get(id=student_id)
			result = Result.objects.get(id=result_id)

			total_nomination_score = request.POST.get("total_nomination_score")
			given_nomination_score = request.POST.get("given_nomination_score")

			result.score += int(given_nomination_score)
			result.total += int(total_nomination_score)

			result.percentage = (result.score/result.total)*100
			
			result.save()


			return HttpResponseRedirect(reverse("result:all_result"))

			
		else:
			result = Result.objects.get(id=result_id)
			response_nf = NominationForm.objects.get(id=result.response_nomination_form_id)

			context = {"result": result, "response_nf":response_nf}
			return render(request, 'result/result_detail.html', context)
		
	else:
		return HttpResponse("Не авторизованы!, Свяжитесь с номером 87074440969")		



def EditResultView(request, result_id, student_id):
	student = Student.objects.get(id=student_id)
	result = Result.objects.get(id=result_id)
	if request.method == "POST":
		score = request.POST.get("score")
		total = request.POST.get("total")

		result.score = int(score)
		result.total = int(total)
		result.percentage = (int(score)/int(total))*100
			
		result.save()


		return HttpResponseRedirect(reverse("result:all_result"))


		
	else:
		result = Result.objects.get(id=result_id)
		context = {"result": result}
		return render(request, 'result/edit_result.html', context)

result/templates/result/all_result.html
{% extends 'radmin/base.html' %}
{% load static %}
  

{% block content %}	

        <div class="row">
          <div class="col-md-12">
            <div class="card" style="border-radius: 30px">
              <div class="card-header" style="background-color: #28a745; border-radius:30px 30px 0 0; color: #fff">
                <h3 class="card-title">Результаты</h3>
              </div>
              <!-- /.card-header -->
              {% if results %}
              <div class="card-body">
                {% for result in results %}
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">№</th>
                      <th>ФИО</th>
                      <th>Регистрационный панель</th>
                      <th style="width: 40px">Экзамен(id)</th>
                      <th>Оценка(%)</th>
                      <th>Отметка </th>
                      <th>Изменить результат</th>
                    </tr>
                  </thead>
                  <tbody>
                    
                      
                      {% for item in result %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'result:result_detail' item.id item.student.id %}">
                              {{ item.student.name }}
                            </a>
                        </td>
                        <td>
                          <div>
                            <a href="{% url 'result:result_detail' item.id item.student.id %}">
                              {{ item.student.reg_no }}
                            </a>
                          </div>
                        </td>
                        <td><span class="badge bg-success">
                          <a href="{% url 'result:result_detail' item.id item.student.id %}">
                             {{ item.exam_type }}({{ item.exam_slug }})
                          </a>
                        </span></td>

                        <td><span class="badge bg-danger">
                          <a href="{% url 'result:result_detail' item.id item.student.id %}">
                            {{ item.percentage }}%
                          </a>
                        </span></td>

                      <td>
                          <a href="{% url 'result:result_detail' item.id item.student.id %}">
                            Пройдено
                          </a>
                      </td>

                      <td>
                          <a href="{% url 'result:edit_result' item.id item.student.id %}">
                            Изменить
                          </a>
                      </td>

                      </tr>

                      {% endfor %}
                      

                    


                  </tbody>
                </table>
                <hr>
                <br />
                {% endfor %}
              </div>
              {% else %}
                <div class="card-body">
                 <p>Извините, Ничего не найдено!</p>
                </div>
              {% endif %}

          </div>

            <!-- /.card -->
      </div>



        </div>
            
{% endblock content %}

result/templates/result/edit_result.html
{% extends 'radmin/base.html' %}
{% load static %}
  

{% block content %}

                   
                    <form method="post" enctype="multipart/form-data">
                    	{% csrf_token %}
                        <div class="row">
                        

							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="card" style="border-radius: 30px;">
                                    <div class="card-header" style="background-color: #28a745; border-radius:30px 30px 0 0; color: #fff">Редактировать результат экзамена</div>
                                    <div class="card-body">
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Учащийся:</label>
                                                    <small>{{ result.student.name }}({{ result.student.reg_no }})</small>
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Набранные баллы:</label>
                                                <small>{{ result.score }}/{{ result.total }}({{ result.percentage }})%</small>
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Укажите свой балл за этого студента (только за теорию, форму номинации и посещаемость!):</label>
                                                <input id="cc-name" name="score" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your phone"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" value="{{ result.score }}">
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Максимальный балл (только за теорию, форму номинации и посещаемость!):</label>
                                                <input id="cc-name" name="total" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your phone"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" value="{{ result.total }}">
                                            </div>
                                            <hr>
                                            <br />


                                        
                                    </div>
                                </div>
                            </div>
                                
                                
                                                                
                                
						</div>	
						
						<div class="row">
							<div class="col-lg-12 col-md-8 col-sm-6 col-xs-4">
                                <button id="payment-button" type="submit" class="btn btn-lg btn-block btn btnsuccess" style="border-radius: 30px">
                                   <span id="payment-button-amount" class="btn btn-success" style="border-radius: 30px">Сохранить данные</span>
                                   <span id="payment-button-sending" style="display:none;">Отправка..</span>
                                </button>
                            </div>
						</div>
				 </form>

    <br />
  	
  	

        
       
{% endblock content %}

result/templates/result/result_detail.html
{% extends 'radmin/base.html' %}
{% load static %}
  

{% block content %}

                   
                    <form method="post" enctype="multipart/form-data">
                    	{% csrf_token %}
                        <div class="row">
                        

							<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="card" style="border-radius: 30px;">
                                    <div class="card-header" style="background-color: #28a745; border-radius:30px 30px 0 0; color: #fff">Пройденный экзамен</div>
                                    <div class="card-body">
                                            <div class="form-group">
                                                <label for="cc-payment" class="control-label mb-1">Учащийся:</label>
                                                    <small>{{ result.student.name }}({{ result.student.reg_no }})</small>
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Набранные баллы:</label>
                                                <small>{{ result.score }}/{{ result.total }}({{ result.percentage }})%</small>
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Ответы на формы:</label>
                                                <br />
                                                <small><b>ФИО:</b> {{ response_nf.name_one }}</small><br />
                                                <small><b>Телефон:</b> {{ response_nf.phone_one }}</small><br />
                                                <small><b>Группа:</b> {{ response_nf.qualification_one }}</small><br />
                                                <small><b>Местоположение:</b> {{ response_nf.residental_state_one }}</small>
                                                <hr>
                                                <br />
                                               <!-- <small><b>ФИО:</b> {{ response_nf.name_two }}</small><br />
                                                <small><b>Телефон:</b> {{ response_nf.phone_two }}</small><br />
                                                <small><b>Группа:</b> </small>{{ response_nf.qualification_two }}</small><br />
                                                <small><b> Местоположение:</b> {{ response_nf.residental_state_two }}</small>-->
                                                <hr>
                                                <br />
                                                <!--<small><b>ФМО:</b> {{ response_nf.name_two }}</small><br />
                                                <small><b>Телефон:</b> {{ response_nf.phone_two }}</small><br />
                                                <small><b>Группа:</b> {{ response_nf.qualification_two }}</small><br />
                                                <small><b> Местоположение:</b> {{ response_nf.residental_state_two }}</small>-->
                                                <hr>
                                            </div>
                                            <br />
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Ответы на теоретические вопросы:</label>
                                                <br />
                                                <small>{{ result.response_theory }}</small>
                                            </div>
                                            <br />
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Укажите свой балл за этого студента (только за теорию, форму номинации и посещаемость!):</label>
                                                <input id="cc-name" name="given_nomination_score" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your phone"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" required="required">
                                            </div>
                                            <div class="form-group has-success">
                                                <label for="cc-name" class="control-label mb-1">Максимальный балл (только за теорию, форму номинации и посещаемость!):</label>
                                                <input id="cc-name" name="total_nomination_score" type="text" class="form-control cc-name valid" data-val="true" data-val-required="Please enter your phone"
                                                    autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error" required="required">
                                            </div>
                                            <hr>
                                            <br />


                                        
                                    </div>
                                </div>
                            </div>
                                
                                
                                                                
                                
						</div>	
						
						<div class="row">
							<div class="col-lg-12 col-md-8 col-sm-6 col-xs-4">
                                <button id="payment-button" type="submit" class="btn btn-lg btn-block btn btn-success" style="border-radius: 30px">
                                   <span id="payment-button-amount" class="btn btn-success" style="border-radius: 30px">Отправить</span>
                                   <span id="payment-button-sending" style="display:none;">Отправка..</span>
                                </button>
                            </div>
						</div>
				 </form>

    <br />
  	
  	

        
       
{% endblock content %}