exam/urls.py
from django.urls import path
from . import views

app_name = "exam"

urlpatterns = [

    path('add-exam/', views.AddExamView, name='add_exam'),
    path('exam-detail/<int:id>/', views.ExamDetailView, name='exam_detail'),
    path('edit-exam/<int:id>/', views.EditExamView, name='edit_exam'),
    path('all-exam/', views.AllExamView, name='all_exam'),

]

exam_portal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("", include("radmin.urls")),
    path("", include("sadmin.urls")),

    path("", include("student.urls")),
    path("", include("exam.urls")),
    path("", include("theory.urls")),
    path("", include("nomination_form.urls")),
    path("", include("result.urls")),

    path("", include("question.urls")),
    path("", include("answer.urls")),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

	path("", views.LoginView, name="login"),
	path("sign-up/", views.SignUpView, name="sign_up"),

	path("e/<str:exam_slug>/<str:exam_link>/", views.ExamLoginView, name="exam_login"),
	path("e/<str:exam_link>/<int:student_id>/start/", views.TakeExamView, name="take_exam"),
	path("e/<str:exam_link>/<int:student_id>/<int:result_id>/nomination_form/", views.TakeExamNView, name="take_exam_n"),
	path("e/<str:exam_link>/<int:student_id>/<int:result_id>/theory/", views.TakeExamTView, name="take_exam_t"),
	path("e/<str:exam_link>/<int:student_id>/exam-complete/", views.ExamCompleteView, name="exam_complete"),
	path("e/<str:exam_link>/<int:student_id>/error/", views.ErrorView, name="error"),

	path("e/<str:exam_slug>/exam-complete/result-checker/", views.ResultCheckerView, name="result_checker"),
	path("e/<str:exam_slug>/<int:student_id>/exam_complete/result-checker/complete/", views.StudentResultView, name="student_result"),

	path("e/time-up-submit/<str:exam_link>/<int:student_id>/r/complete-time-up-submit/", views.TimeUpSubmitView, name="time_up_submit"),
	
	path("userlogout/", views.UserLogoutView, name="userlogout"),

]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password1 = forms.CharField(widget=forms.PasswordInput())
	password2 = forms.CharField(widget=forms.PasswordInput())
	class Meta():
		model = User
		fields = ("username", "password1", "password2")

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate

from .forms import UserForm

from student.models import Student
from exam.models import Exam, ExamStudentConnector
from nomination_form.models import NominationForm
from theory.models import Theory
from result.models import Result
from radmin.models import RAdmin
from django.contrib import messages

# Create your views here.

def SignUpView(request):
	if request.method == "POST":
		form = UserForm(request.POST or None, request.FILES or None)
		
		if request.POST.get("password2") != request.POST.get("password1"):
			return HttpResponse("Error!  -Please make sure both passwords are similar")
			
		else:
			user = form.save()
			user.set_password(request.POST.get("password1"))
			user.save()

			login(request, user)

			status = "not-verified"
			radmin = RAdmin.objects.create(user=user, name=user.username, status=status)
			radmin.save()

			return HttpResponseRedirect(reverse("main:login"))
	
	else:
		form2 = UserForm()
		return render(request, "main/sign_up.html", {"form2": form2})






def LoginView(request):
	if request.method == "POST":
		username = request.POST.get("username")
		password = request.POST.get("password")
		status = request.POST.get("account_type")

		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(reverse("radmin:radmin"))
			else:
				messages.success(request, "Неправильный пароль или логин")
				return HttpResponseRedirect(reverse("main:login"))

		else:
			messages.success(request, "Неправильный пароль или логин")
			return HttpResponseRedirect(reverse("main:login"))
	else:
		context = {}
		return render(request, "main/login.html", context)



def ExamLoginView(request, exam_slug, exam_link):
	exam = Exam.objects.get(id=exam_link)
	if exam.status == True:
		if request.method == "POST":
			reg_no = request.POST.get("reg_no")

			user = authenticate(username=reg_no, password=reg_no)

			try:
				student = Student.objects.get(user__pk=user.id, reg_no=reg_no)
			except:
				student = None

			if user and student:
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect(reverse("main:take_exam", args=(exam_link, student.id,)))
				else:
					messages.success(request, "Incorrectly ID")
					return HttpResponseRedirect(reverse("main:error", args=(exam_link, exam_link,)))

			else:
				messages.success(request, "Incorrectly ID")
				return HttpResponseRedirect(reverse("main:error", args=(exam_link, exam_link,)))



		else:
			context = {}
			return render(request, "main/exam_login.html", context)

	else:
		
		return HttpResponse("Извините, Этот экзамен либо еще не начался, либо уже закончился! Свяжитесь с преподавателем.")



def TakeExamView(request, exam_link, student_id):
	status = "off" #status check if student already wrote the exam
	exam = Exam.objects.get(id=exam_link)
	exam_title = exam.title
	exam_type = exam.exam_type
	exam_slug = exam.exam_slug
	student = Student.objects.get(id=student_id)

	#for time up shit
	time_exam_link = exam.id
	time_student_id = student.id
	#time_result_id = 9999999999999999999999999999999999

	for item in exam.students.all():
		if item.id == student_id:
			status = "on"


	if status == "off":
		questions = exam.questions.all()
		counts = exam.questions.count()
		count_list = []


		for i in range(counts):
			count_list.append(i+1)

		exam_questions = zip(questions, count_list)

		if request.method == "POST":
			score = 0
			percentage = 0
			actual_score = 0
			real_score = 0

			answers = []
			answer_list = []
			for item, count in exam_questions:
				val = "selected_answer_" + str(count)
				if request.POST.get(val):
					answers.append(request.POST.get(val))
				else:
					answers.append("x_x")

			for item in answers:
				answer_list.append(item.split("_")[1])


			for item, item2 in zip(exam.questions.all(), answer_list):
				if item.real_answer == item2:
					actual_score += 1

			percentage = (actual_score/counts)*100

			#return HttpResponse(percentage)

			
			result = Result.objects.create(student=student, exam_id=exam_link, exam_title=exam_title, exam_type=exam_type, exam_slug=exam_slug,
			 answers=answer_list, score=actual_score, total=counts, percentage=percentage)
			result.save()

			return HttpResponseRedirect(reverse("main:take_exam_n", args=(exam_link, student.id, result.id,)))


		else:
			context = {"exam": exam, "exam_questions": exam_questions, "time_exam_link": time_exam_link, "time_student_id": time_student_id}#, "time_result_id": time_result_id}
			return render(request, "main/take_exam.html", context)

	else:
		messages.success(request, "Извините, Вы уже прошли этот экзамен!")
		return HttpResponseRedirect(reverse("main:error", args=(exam_link, student.id,)))

def TakeExamNView(request, exam_link, student_id, result_id):
	exam = Exam.objects.get(id=exam_link)
	student = Student.objects.get(id=student_id)
	result = Result.objects.get(id=result_id)

	#for time up shit
	time_exam_link = exam.id
	time_student_id = student.id
	#time_result_id = result.id

	if request.method == "POST":
		

		name_1 = request.POST.get("name_1")
		#name_2 = request.POST.get("name_2")
		#name_3 = request.POST.get("name_3")

		phone_1 = request.POST.get("phone_1")
		#phone_2 = request.POST.get("phone_2")
		#phone_3 = request.POST.get("phone_3")

		qualification_1 = request.POST.get("qualification_1")
		#qualification_2 = request.POST.get("qualification_2")
		#qualification_3 = request.POST.get("qualification_3")

		residental_state_1 = request.POST.get("residental_state_1")
		#residental_state_2 = request.POST.get("residental_state_2")
		#residental_state_3 = request.POST.get("residental_state_3")

		nomination_form = NominationForm.objects.create(name_one=name_1, phone_one=phone_1, qualification_one=qualification_1, residental_state_one=residental_state_1,
			#name_two=name_2, phone_two=phone_2, qualification_two=qualification_2, residental_state_two=residental_state_2,
			#name_three=name_3, phone_three=phone_3, qualification_three=qualification_3, residental_state_three=residental_state_3
			)
		result.response_nomination_form_id = nomination_form.id
		result.save()
		

		return HttpResponseRedirect(reverse("main:take_exam_t", args=(exam_link, student.id, result.id)))


	else:
		

		context = {"exam": exam, "time_exam_link": time_exam_link, "time_student_id": time_student_id}#, "time_result_id": time_result_id}
		return render(request, "main/take_exam_n.html", context)




def TakeExamTView(request, exam_link, student_id, result_id):
	exam = Exam.objects.get(id=exam_link)
	student = Student.objects.get(id=student_id)
	result = Result.objects.get(id=result_id)

	theorys = exam.theorys.all()
	counts = exam.theorys.count()
	count_list = []

	for i in range(counts):
		count_list.append(i+1)

	exam_theorys = zip(theorys, count_list)


	#for time up shit
	time_exam_link = exam.id
	time_student_id = student.id
	#time_result_id = result.id


	if request.method == "POST":

		response_theory = ""
		for item, count in exam_theorys:
			val = "answer_" + str(count)
			response_theory = response_theory + ("Q%s: %s(Answer: %s) | " % (count, item.title, request.POST.get(val)))

		result.response_theory = response_theory
		result.save()

		exam_student = ExamStudentConnector(exam=exam, student=student)
		exam_student.save()

		logout(request)
		return HttpResponseRedirect(reverse("main:exam_complete", args=(exam_link, student.id,)))


	else:

		context = {"exam": exam, "exam_theorys": exam_theorys, "time_exam_link": time_exam_link, "time_student_id": time_student_id}#, "time_result_id": time_result_id}
		return render(request, "main/take_exam_t.html", context)






def TimeUpSubmitView(request, exam_link, student_id):
	#request.method == "POST"
	#TakeExamView(request=request, exam_link=exam_link, student_id=student_id)

	try:
		status = "off" #status check if student already wrote the exam
		exam = Exam.objects.get(id=exam_link)
		exam_title = exam.title
		exam_type = exam.exam_type
		exam_slug = exam.exam_slug
		student = Student.objects.get(id=student_id)


		for item in exam.students.all():
			if item.id == student_id:
				status = "on"


		if status == "off":
			questions = exam.questions.all()
			counts = exam.questions.count()
			count_list = []


			for i in range(counts):
				count_list.append(i+1)

			exam_questions = zip(questions, count_list)

			score = 0
			percentage = 0
			actual_score = 0
			real_score = 0

			answers = []
			answer_list = []
			for item, count in exam_questions:
				val = "selected_answer_" + str(count)
				if request.POST.get(val):
					answers.append(request.POST.get(val))
				else:
					answers.append("x_x")

			for item in answers:
				answer_list.append(item.split("_")[1])


			for item, item2 in zip(exam.questions.all(), answer_list):
				if item.real_answer == item2:
					actual_score += 1

			percentage = (actual_score/counts)*100

			#return HttpResponse(percentage)

			
			result = Result.objects.create(student=student, exam_id=exam_link, exam_title=exam_title, exam_type=exam_type, exam_slug=exam_slug,
			 answers=answer_list, score=actual_score, total=counts, percentage=percentage)
			result.save()

		else:
			messages.success(request, "Извините, Но вы уже прошли этот экзамен!")
			return HttpResponseRedirect(reverse("main:error", args=(exam_link, student.id,)))
			


	except:
		pass


	try:
		exam = Exam.objects.get(id=exam_link)
		student = Student.objects.get(id=student_id)
		result = Result.objects.get(id=result_id)

		#for time up shit
		time_exam_link = exam.id
		time_student_id = student.id
		time_result_id = result.id

			

		name_1 = request.POST.get("name_1")
		name_2 = request.POST.get("name_2")
		name_3 = request.POST.get("name_3")

		phone_1 = request.POST.get("phone_1")

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="codepixer">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Экзамен</title>
	

	<!--
			Google Font
			============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,500,600" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500i" rel="stylesheet">

	<!--
			CSS
			============================================= -->
	<link rel="stylesheet" href="{% static 'main/https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/animate.min.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
	<meta charset="utf-8">
    <meta name="description" content="">
    <meta name="keywords" content="">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>


<style type="text/css">
.check-box-group {
  display: flex;
  flex-direction: column;
  
}

.custom-checkbox {
  cursor: pointer;
  display: flex;
  align-items: center;
  margin: 10px 0;
}

.custom-checkbox .label {
  font-size: 1.2em;
  margin: 0 10px;
}

.custom-checkbox .checkmark {
  width: 35px;
  height: 35px;
  border: 2px solid #222;
  display: inline-block;
  border-radius: 3px;
  background: #009900 url(https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/White_check.svg/1200px-White_check.svg.png) center/1250% no-repeat;
  cursor: pointer;

  transition: background-size 0.2s ease;
}

.custom-checkbox input:checked + .checkmark {
  background-size: 60%;
  color: #fff;
  cursor: pointer;
  transition: background-size 0.25s cubic-bezier(0.7, 0, 0.18, 1.24);
}

.custom-checkbox input {
  display: none;
}
</style>

<body>

	<!-- Start Header Area -->
	<header id="header">

		<div class="container">
		<div class="row d-flex" style="justify-content: right; float: right;">
		<nav id="nav-menu-container" style="justify-content: right; float: right;">
			<ul class="nav-menu">
				
				<li><div class="timer" onload="timer({{ exam.duration }})">
				  <div>Экзамен</div>
				  <div class="time">
				    <strong>Осталось времени: <span id="time">Loading...</span></strong>
				  </div>
				</li>
				
				<li><p id="ray_counter"></p></li>
			
			</ul>
		</nav>
			</div>
		</div>
	</header>
	<!-- End Header Area -->





			{% block content %}



			{% endblock %}


	

<!-- Start Footer Area -->
	<footer class="footer-area">
		<div class="container">
			<div class="row">
				
			</div>
			<div class="footer-bottom row align-items-center">
				<!--<p class="footer-text m-0 col-lg-6 col-md-12">--><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
 <!--&copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>-->
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				<!--<div class="col-lg-4 col-md-12 footer-social">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-behance"></i></a>-->
				</div>
			</div>
		</div>
	</footer>
	<!-- End Footer Area -->

	<!-- ####################### Start Scroll to Top Area ####################### -->
	<div id="back-top">
		<a title="Go to Top" href="#"></a>
	</div>
	<!-- ####################### End Scroll to Top Area ####################### -->

</body>

	<script src="{% static 'main/js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="{% static 'main/js/vendor/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
	<script src="{% static 'main/js/easing.min.js' %}"></script>
	<script src="{% static 'main/js/hoverIntent.js' %}"></script>
	<script src="{% static 'main/js/superfish.min.js' %}"></script>
	<script src="{% static 'main/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'main/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'main/js/owl-carousel-thumb.min.js' %}"></script>
	<script src="{% static 'main/js/jquery.sticky.js' %}"></script>
	<script src="{% static 'main/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'main/js/parallax.min.js' %}"></script>
	<script src="{% static 'main/js/waypoints.min.js' %}"></script>
	<script src="{% static 'main/js/wow.min.js' %}"></script>
	<script src="{% static 'main/js/jquery.counterup.min.js' %}"></script>
	<script src="{% static 'main/js/mail-script.js' %}"></script>
	<script src="{% static 'main/js/main.js' %}"></script>
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="{% static 'main/js/kinetic.js' %}"></script>
<script type="text/javascript" src="{% static 'main/jquery.final-countdown.js' %}"></script>
<script>
	var time = {{ exam.duration }};
	setInterval(function() {
	  var seconds = time % 60;
	  var minutes = (time - seconds) / 60;
	  if (seconds.toString().length == 1) {
	    seconds = "0" + seconds;
	  }
	  if (minutes.toString().length == 1) {
	    minutes = "0" + minutes;
	  }
	  document.getElementById("time").innerHTML = minutes + ":" + seconds;
	  time--;
	  if (time == 0) {
	    window.location.href = "{% url 'main:time_up_submit' time_exam_link time_student_id %}";
	  }
	}, 1000);
</script>

</body>

</html>

main/templates/main/error.html
{% extends 'main/basee.html'%}
{% load static %}

{% block content %}

<!-- Start Faculty Area -->
	<section class="faculty-area section-gap">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-12">
					<div class="section-title">
						<div class="row  d-flex align-items-center">
							<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex" style="text-align: center; justify-content: center;">
										

										

									</div>


							</div>
						</div>

						<div class="row  d-flex align-items-center">
							<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex" style="text-align: center; justify-content: center;">
										{% if messages %}
    									{% for message in messages %}
    									<h5 class="alert alert-{{message.tags}} text-center" role="alert" style="background: transparent; color: #000;">
    									{{ message }}
    									</h5>
    									{% endfor %}     
									{% endif %}
										

									</div>




							</div>
						</div>
					</div>
					<div class="section-title">

						<div class="row  d-flex align-items-center">
							<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex" style="text-align: center; justify-content: center;">
										<button class="btn btn-success"><a href="{% url 'main:exam_login' exam.exam_slug exam.id %}" style="color: #fff; justify-content: center;">На главную</a></button>

										

									</div>


							</div>
						</div>
					</div>
				</div>
			</div>
			
	
		</div>

</section>

{% endblock %}

main/templates/main/exam_complete.html
{% extends 'main/basee.html'%}
{% load static %}

{% block content %}

<!-- Start Faculty Area -->
	<section class="faculty-area section-gap">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-12">
					<div class="section-title">
						<div class="row  d-flex align-items-center">
							<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex" style="text-align: center; justify-content: center;">
										<h1>Поздравляем!!!</h1>

										

									</div>


							</div>
						</div>

						<div class="row  d-flex align-items-center">
							<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex" style="text-align: center; justify-content: center;">
										<p>Вы закончили свой экзамен!.</p>

										

									</div>


							</div>
						</div>
					</div>
					<div class="section-title">

						<div class="row  d-flex align-items-center">
							<div class="col-lg-12 col-md-6 col-sm-12 single-faculty">
									<div class="thumb d-flex" style="text-align: center; justify-content: center;">
										<button class="btn btn-success"><a href="{% url 'main:exam_login' exam.exam_slug exam.id %}" style="color: #fff; justify-content: center;">На главную</a></button>

										

									</div>


							</div>
						</div>
					</div>
				</div>
			</div>
			
	
		</div>
		<br>
		<br>
		<br>
		<br>
		<br>



</section>

{% endblock %}

main/templates/main/exam_login.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Экзамен | Войти</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'tutor/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'tutor/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'tutor/dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition login-page" background="src" style="background-image:url({% static 'main/img/header-bg.png'%}); background-size: cover;">
<div class="login-box">
  <div class="login-logo">

    <h1 class="wow fadeIn" data-wow-duration="4s" style="color: #fff">Авторизация учащегося</h1>
  </div>
  <!-- /.login-logo -->
  <div class="card" style="background:transparent; border-color: #fff; border-radius: 20px; border-style: 10px bold" >
    <div class="card-body login-card-body" style="background-color: #fff; background: transparent; border-radius: 20px; border-style: 10px bold" >
      <p class="login-box-msg" style="color: #fff">Логин</p>


            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label style="color: #fff">Регистрационный номер:</label>
                    <br>
                    <div class="input-group mb-3">
                    <input type="password" class="form-control" name="reg_no" placeholder="Регистрационный номер" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                         <span class="fas fa-lock"></span>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="login-checkbox">
                    <br>
                    <label>
                        <input type="checkbox" name="remember"> Запомнить меня
                    </label>
                    
                    <label>
                        <!--<a href="#">Forgotten reg.no?</a>-->
                    </label>
                    <br>
                </div>
                 <br>
      <br>
                <button type="submit" class="btn btn-success" style="border-radius:10px 0 10px 0; align-items: center; justify-content: center; ">Логин!</button>
               
                
            </form>

    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static '../tutor/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static '../titor/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static '../tutor/dist/js/adminlte.min.js' %}"></script>

</body>
</html>

main/templates/main/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Логин</label>
        <input class="au-input au-input--full" type="text" name="username" placeholder="Username" required="required">
    </div>
    <div class="form-group">
        <label>Пароль</label>
        <input class="au-input au-input--full" type="password" name="password1" placeholder="Password" required="required">
    </div>
    <div class="form-group">
        <label>Password</label>
        <input class="au-input au-input--full" type="password" name="password2" placeholder="Confirm Password" required="required">
    </div>
    <div class="login-checkbox">
        <label>
            <input type="checkbox" name="remember">Remember Me
        </label>
        <label>
            <a href="#">Forgotten Password?</a>
        </label>
    </div>
    <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">Sign Up</button>
    <div class="social-login-content">
        <div class="social-button">
            <a href="#" class="au-btn au-btn--block au-btn--blue m-b-20">sign in with facebook</a>
          <a href="#" class="au-btn au-btn--block au-btn--blue2">sign in with twitter</a>
        </div>
    </div>
</form>
{% endblock %}